# -*- coding: utf-8 -*-
"""HW3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xkyy0pKJHVgKxS24S91RNNWeKuZCU7Q7
"""

#設定作業demo
demo = [33, 67, 8, 13, 54, 119, 3, 84, 25, 41]

#定義QuickSort函數
def QuickSort(array, start, end):

  #if (array length == 1):
  if (start >= end):
    return

  pivot = start
  left = start
  right = end

  while (left != right):
    #當右指標比基準點大時，移動右指標向左
    while (array[right] >= array[pivot]) and (left < right):
      right -= 1
    #當左指標比基準點小時，移動左指標向右
    while (array[left] <= array[pivot]) and (left < right):
      left += 1
    #交換左右指標
    array[left], array[right] = array[right], array[left]
    #印出排序過程
    print(f"{array}")

  #交換基準點與指標
  array[pivot], array[right] = array[right], array[pivot]

  #開始新一輪的Quiclsort
  QuickSort(array, start, right - 1)
  QuickSort(array, right + 1, end)

print("Original:", demo, "\n")
QuickSort(demo, 0, len(demo) - 1)
print("\nSorted:", demo)